title: thedevmanager.com

exclude:
- README.md
- API.md
- Gemfile
- Gemfile.lock

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/api/v1/facts/:title.json"

sass:
  style: compressed