title: thedevmanager.com

exclude:
- README.md
- API.md
- Gemfile
- Gemfile.lock
- netlify.toml

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/api/v1/facts/:title.json"

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: ""
  indexpage: ":num"
  sort_field: "sort"
  extension: "json"