[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "https://chickenfacts.io.netlify.com/*"
  to = "https://chickenfacts.io/:splat"
  status = 301

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
